### ISSUE TITLE
ZM TODO

### ISSUE THREAD

**Issue by Makowo** [Painday2/SkyLib#1]
- [X] Special waves
- [x] Weapon Switch
- [x] Perks -- would like to rework these into seperate interactionext's 
- [x] Quick Revive Ext
- [x] Jug Ext
- [x] SpeedCola Ext
- [x] DoubleTap Ext
- [x] Deadshot Ext
- [x] Stamin Ext
- [x] Wall buys -- need to add tweak data stuff. fun
- [ ] replace revive symbol with cod revive
- [x] Mystery box ext 
- [x] mystery box anims and weapons
- [x] PAP -- Works, needs some improvements with how to tell pap level, also upgrading ammo, unsure of how to math, also reworking into interactionExt
- [ ] PAP Skins -- have one that """works""" but need to ask if anyone wants to actually make a good skin or two
- [x] funky things like round end contours
- [ ] any """"Reborn"""" improvements
- [x] Loading assets from mod folder - sounds work now, via jank adding of an extra mod
- [ ] ask about using animated skins - rex gave idea of using them to determine ammo types
